name: emad_client
description: "CAApp"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  get: ^4.6.6
  lottie: ^3.1.3
  animated_text_kit: ^4.2.2
  simple_gradient_text: ^1.3.0
  shared_preferences: ^2.3.3
  speech_to_text: ^7.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/icons/

flutter_intl:
  enabled: true