// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfKYoKOJ3RRr1KBXtTCk6YhvMbXiMPQ4',
    appId: '1:569675897050:web:2adeb6340dc67f7cd6ede3',
    messagingSenderId: '569675897050',
    projectId: 'emad-caapp',
    authDomain: 'emad-caapp.firebaseapp.com',
    storageBucket: 'emad-caapp.firebasestorage.app',
    measurementId: 'G-C0S92ZPSJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xHC-K3_LAkdeYDvS7xhbZumXOWp-VMk',
    appId: '1:569675897050:android:32dd0496a0465b29d6ede3',
    messagingSenderId: '569675897050',
    projectId: 'emad-caapp',
    storageBucket: 'emad-caapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmfKYoKOJ3RRr1KBXtTCk6YhvMbXiMPQ4',
    appId: '1:569675897050:web:52f11de8f11bf8b4d6ede3',
    messagingSenderId: '569675897050',
    projectId: 'emad-caapp',
    authDomain: 'emad-caapp.firebaseapp.com',
    storageBucket: 'emad-caapp.firebasestorage.app',
    measurementId: 'G-89GL85FDCC',
  );
}
